---
# tasks file for docker-registry
- name: logging into dockerhub
  docker_login:
    username: rihab96
    password: docker2022
- name: push image to dockerhub
  repository: rihab96/lcproject
  tag: latest
  source: local
  push: yes
